stages: 
  - deploy

test :
  stage: deploy

  before_script:
    - echo 'start deployment' 
  script:
    - echo 'script ing'
    - ls
    - git remote -v
    - git pull origin master
  after_script:
    - echo 'deployment is done'
  tags:
    - deploy
