stages: 
  - deploy
  - build

test :
  stage: deploy

  before_script:
    - echo 'start deployment' 
  script:
    - echo 'script ing'
  after_script:
    - echo 'deployment is done'
  tags:
    - deploy
