spring:
  application:
    name: sweethome
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sweethome;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    include: oauth
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: sweethomead11@gmail.com
    password: aktxxkpajugestha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: 8080

jwt:
  token:
    header-type: JWT
    issuer: 2030
    secret: b3JpX3RveV9wcm9qZWN0X3JlYWxfd29ybGRfamF2YV9zcHJpbmdfYm9vdF9zZWNyZXRfand0X3NhdWx0X2tleQo=
    access-time: 1800000  # 30분
    refresh-time: 604800000 # 7일

cloud:
  aws:
    credentials:
      accessKey: AKIA2SSL7OZDV5KIQXR3
      secretKey: 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
    s3:
      bucket: sweethome-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false