spring:
  application:
    name: sweethome
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sweethome;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

jwt:
  token:
    header-type: JWT
    issuer: 2030
    secret: b3JpX3RveV9wcm9qZWN0X3JlYWxfd29ybGRfamF2YV9zcHJpbmdfYm9vdF9zZWNyZXRfand0X3NhdWx0X2tleQo=
    access-time: 1800000  # 30분
    refresh-time: 604800000 # 7일
